### ISSUE TITLE
Lib fails to connect on MKR1400

### ISSUE THREAD

**Issue by fabltd** [khoih-prog/GSM_Generic#5] opened 2021-07-28 19:44 UTC
### Describe the bug

Testing on MKR 1400 fails:

Starting GSMScanNetworks on SAMD MKRGSM1400
GSM_Generic v1.4.0
GSM networks scanner
[GSM] begin: UART baud = 115200
AT+CFUN=16
[GSM] begin: reset error

### Steps to Reproduce

Using the default network scanner with MKRGSM works.

Using the default network scanner with GSM_Generic fails.

### Expected behavior

Connection to module and GSM networks reported.

### Information

Please ensure to specify the following:

* Arduino IDE version (e.g. 1.8.13) or Platform.io version

Platform IO 5.1.1 - 3.3.4

SAMD21 - MKR 1400

**Comment by khoih-prog** [comment] 2021-07-30 19:28
Thanks for your interest in the library, which is modified and written mostly for other boards besides **MKRGSM 1400 / SARA U201**

Can you try the original [**MKRGSM** library](https://github.com/arduino-libraries/MKRGSM) and with **Arduino IDE** to see if it's working OK or not, to be sure that the issue is not related to board **hardware failure, SIM, network, power supply**, etc ?

Only if everything is OK, the move on gradually to PIO, etc. to know which is the culprit.

I also can't help any further as I don't have the same MKRGSM 1400 / SARA U201 to test.

Anyway, I'll close this issue and won't reopen until you have more info to prove this is the bug of this library.

Good Luck,

**Closed as completed by khoih-prog** 2021-07-30 19:28 UTC
Labels: Support
